---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: prometheus-blackbox-exporter
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus-blackbox-exporter
    version: 1.3.0
  values:
    image:
      repository: prom/blackbox-exporter
      tag: v0.15.0
      pullPolicy: IfNotPresent

    secretConfig: false
    config:
      modules:
        http_2xx:
          prober: http
          timeout: 5s
          http:
            method: GET
            valid_http_versions: ["HTTP/1.1", "HTTP/2"]
            valid_status_codes:
            - 401
            - 403
            - 200
            - 301
            - 302
            - 307
            no_follow_redirects: false
            fail_if_ssl: false
            fail_if_not_ssl: false
            preferred_ip_protocol: "ip4"
            tls_config:
              insecure_skip_verify: false
        http_post_2xx:
          prober: http
          timeout: 5s
          http:
            method: POST
            headers:
              Content-Type: application/json
            body: '{}'

    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 50Mi

    serviceMonitor:
      ## If true, a ServiceMonitor CRD is created for a prometheus operator
      ## https://github.com/coreos/prometheus-operator
      ##
      enabled: false
      labels: {}
      interval: 30s
      scrapeTimeout: 30s
      module: http_2xx
      # The URL that blackbox will scrape
      url: http://example.com/healthz
      # Optional human readable URL that will appear in Prometheus / AlertManager
      urlHumanReadable:  # www.changemeoriwillfail.com
